program WebkassaAccTest;

uses
  FastMM4,
  SysUtils,
  TestFramework,
  GUITestRunner,
  LogFile in '..\..\src\Shared\LogFile.pas',
  Opos in '..\..\src\Opos\OPOS.pas',
  OposUtils in '..\..\src\Opos\OposUtils.pas',
  OposEvents in '..\..\src\Opos\OposEvents.pas',
  OposFptr in '..\..\src\Opos\OposFptr.pas',
  OposFptrhi in '..\..\src\Opos\OposFptrhi.pas',
  Oposhi in '..\..\src\Opos\Oposhi.pas',
  OposStat in '..\..\src\Opos\OposStat.pas',
  OposSemaphore in '..\..\src\Opos\OposSemaphore.pas',
  OposFptrUtils in '..\..\src\Opos\OposFptrUtils.pas',
  OPOSException in '..\..\src\Opos\OposException.pas',
  WException in '..\..\src\Shared\WException.pas',
  WebkassaClient in '..\..\src\OposWebkassa\units\WebkassaClient.pas',
  JsonUtils in '..\..\src\Shared\JsonUtils.pas',
  FileUtils in '..\..\src\Shared\FileUtils.pas',
  duStorePoint in 'units\duStorePoint.pas',
  OposEventsRCS in '..\..\src\Opos\OposEventsRCS.pas',
  DebugUtils in '..\..\src\Shared\DebugUtils.pas',
  OposWebkassaLib_TLB in '..\..\src\OposWebkassa\OposWebkassaLib_TLB.pas',
  OposServiceDevice19 in '..\..\src\Opos\OposServiceDevice19.pas',
  NotifyThread in '..\..\src\Shared\NotifyThread.pas',
  VersionInfo in '..\..\src\Shared\VersionInfo.pas',
  DriverError in '..\..\src\Shared\DriverError.pas',
  FiscalPrinterState in '..\..\src\OposWebkassa\units\FiscalPrinterState.pas',
  CustomReceipt in '..\..\src\OposWebkassa\units\CustomReceipt.pas',
  NonfiscalDoc in '..\..\src\OposWebkassa\units\NonfiscalDoc.pas',
  ServiceVersion in '..\..\src\Shared\ServiceVersion.pas',
  DeviceService in '..\..\src\Shared\DeviceService.pas',
  CashOutReceipt in '..\..\src\OposWebkassa\units\CashOutReceipt.pas',
  CashInReceipt in '..\..\src\OposWebkassa\units\CashInReceipt.pas',
  OposPOSPrinter_CCO_TLB in '..\..\src\Opos\OposPOSPrinter_CCO_TLB.pas',
  PrinterParameters in '..\..\src\Shared\PrinterParameters.pas',
  TntIniFiles in '..\..\src\Shared\TntIniFiles.pas',
  SmIniFile in '..\..\src\Shared\SmIniFile.pas',
  StringUtils in '..\..\src\Shared\StringUtils.pas',
  RegExpr in '..\..\src\Shared\RegExpr.pas',
  MathUtils in '..\..\src\OposWebkassa\units\MathUtils.pas',
  duEscPrinterRongta in 'units\duEscPrinterRongta.pas',
  WebkassaImpl in '..\..\src\OposWebkassa\units\WebkassaImpl.pas',
  SalesReceipt in '..\..\src\OposWebkassa\units\SalesReceipt.pas',
  ReceiptItem in '..\..\src\OposWebkassa\units\ReceiptItem.pas',
  OposEsc in '..\..\src\Opos\OposEsc.pas',
  TextDocument in '..\..\src\OposWebkassa\units\TextDocument.pas',
  OposPtr in '..\..\src\Opos\OposPtr.pas',
  StorePointIO_TLB in 'units\StorePointIO_TLB.pas',
  duWebkassaClient in 'units\duWebkassaClient.pas',
  PrinterParametersReg in '..\..\src\Shared\PrinterParametersReg.pas',
  uLkJSON in '..\..\src\Shared\uLkJSON.pas',
  VatRate in '..\..\src\Shared\VatRate.pas',
  OposPtrUtils in '..\..\src\Opos\OposPtrUtils.pas',
  OposPtrhi in '..\..\src\Opos\OposPtrhi.pas',
  duPrinterTest in 'units\duPrinterTest.pas',
  MockPosPrinter2 in '..\OposWebkassaTest\units\MockPosPrinter2.pas',
  PosPrinterOA48 in '..\..\src\Shared\PosPrinterOA48.pas',
  uZintBarcode in '..\..\src\Shared\uZintBarcode.pas',
  uZintInterface in '..\..\src\Shared\uZintInterface.pas',
  POSPrinterLog in '..\..\src\Opos\POSPrinterLog.pas',
  PosWinPrinter in '..\..\src\Shared\PosWinPrinter.pas',
  ByteUtils in '..\..\src\Shared\ByteUtils.pas',
  duPosPrinterOA48 in 'units\duPosPrinterOA48.pas',
  PrinterPort in '..\..\src\Shared\PrinterPort.pas',
  SerialPort in '..\..\src\Shared\SerialPort.pas',
  DeviceNotification in '..\..\src\Shared\DeviceNotification.pas',
  PortUtil in '..\..\src\Shared\PortUtil.pas',
  TextReport in '..\..\src\Shared\TextReport.pas',
  SocketPort in '..\..\src\Shared\SocketPort.pas',
  duPOSPrinter in 'units\duPOSPrinter.pas',
  SerialPorts in '..\..\src\Shared\SerialPorts.pas',
  ReceiptTemplate in '..\..\src\Shared\ReceiptTemplate.pas',
  duWebkassaImpl in 'units\duWebkassaImpl.pas',
  MockPrinterPort in '..\..\src\Shared\MockPrinterPort.pas',
  RawPrinterPort in '..\..\src\Shared\RawPrinterPort.pas',
  Translation in '..\..\src\Shared\Translation.pas',
  DirectIOAPI in '..\..\src\OposWebkassa\units\DirectIOAPI.pas',
  DriverContext in '..\..\src\Shared\DriverContext.pas',
  PrinterTypes in '..\..\src\Shared\PrinterTypes.pas',
  BarcodeUtils in '..\..\src\Shared\BarcodeUtils.pas',
  MockPosPrinter in '..\OposWebkassaTest\units\MockPosPrinter.pas',
  oleFiscalPrinter in '..\..\src\OposWebkassa\Units\oleFiscalPrinter.pas',
  EscPrinterOA48 in '..\..\src\Shared\EscPrinterOA48.pas',
  EscPrinterPosiflex in '..\..\src\Shared\EscPrinterPosiflex.pas',
  PosPrinterPosiflex in '..\..\src\Shared\PosPrinterPosiflex.pas',
  OposDevice in '..\..\src\Opos\OposDevice.pas',
  duPosPrinterRongta in 'units\duPosPrinterRongta.pas',
  duEscPrinterOA48 in 'units\duEscPrinterOA48.pas',
  EscPrinterUtils in '..\..\src\Shared\EscPrinterUtils.pas',
  PtrDirectIO in '..\..\src\OposWebkassa\units\PtrDirectIO.pas',
  PageBuffer in '..\..\src\OposWebkassa\units\PageBuffer.pas',
  PosPrinterRongta in '..\..\src\Shared\PosPrinterRongta.pas',
  EscPrinterRongta in '..\..\src\Shared\EscPrinterRongta.pas';

{$R *.RES}
{$R ..\..\src\OposWebkassa\OposWebkassa.tlb}

begin
  DecimalSeparator := '.';
  TGUITestRunner.RunTest(RegisteredTests);
end.
