program WebkassaAccTest;

uses
  SysUtils,
  TestFramework,
  GUITestRunner,
  LogFile in '..\..\src\Shared\LogFile.pas',
  Opos in '..\..\src\Opos\OPOS.pas',
  OposUtils in '..\..\src\Opos\OposUtils.pas',
  OposEvents in '..\..\src\Opos\OposEvents.pas',
  OposFptr in '..\..\src\Opos\OposFptr.pas',
  OposFptrhi in '..\..\src\Opos\OposFptrhi.pas',
  Oposhi in '..\..\src\Opos\Oposhi.pas',
  OposStat in '..\..\src\Opos\OposStat.pas',
  OposSemaphore in '..\..\src\Opos\OposSemaphore.pas',
  OposFptrUtils in '..\..\src\Opos\OposFptrUtils.pas',
  OPOSException in '..\..\src\Opos\OposException.pas',
  WException in '..\..\src\Shared\WException.pas',
  WebkassaClient in '..\..\src\OposWebkassa\units\WebkassaClient.pas',
  JsonUtils in '..\..\src\Shared\JsonUtils.pas',
  FileUtils in '..\..\src\Shared\FileUtils.pas',
  duStorePoint in 'units\duStorePoint.pas',
  OposEventsRCS in '..\..\src\Opos\OposEventsRCS.pas',
  DebugUtils in '..\..\src\Shared\DebugUtils.pas',
  OposWebkassaLib_TLB in '..\..\src\OposWebkassa\OposWebkassaLib_TLB.pas',
  OposServiceDevice19 in '..\..\src\Opos\OposServiceDevice19.pas',
  NotifyThread in '..\..\src\Shared\NotifyThread.pas',
  VersionInfo in '..\..\src\Shared\VersionInfo.pas',
  DriverError in '..\..\src\Shared\DriverError.pas',
  FiscalPrinterState in '..\..\src\OposWebkassa\units\FiscalPrinterState.pas',
  CustomReceipt in '..\..\src\OposWebkassa\units\CustomReceipt.pas',
  NonfiscalDoc in '..\..\src\OposWebkassa\units\NonfiscalDoc.pas',
  ServiceVersion in '..\..\src\Shared\ServiceVersion.pas',
  DeviceService in '..\..\src\Shared\DeviceService.pas',
  CashOutReceipt in '..\..\src\OposWebkassa\units\CashOutReceipt.pas',
  CashInReceipt in '..\..\src\OposWebkassa\units\CashInReceipt.pas',
  OposPOSPrinter_CCO_TLB in '..\..\src\Opos\OposPOSPrinter_CCO_TLB.pas',
  PrinterParameters in '..\..\src\Shared\PrinterParameters.pas',
  PrinterParametersX in '..\..\src\Shared\PrinterParametersX.pas',
  PrinterParametersIni in '..\..\src\Shared\PrinterParametersIni.pas',
  TntIniFiles in '..\..\src\Shared\TntIniFiles.pas',
  SmIniFile in '..\..\src\Shared\SmIniFile.pas',
  StringUtils in '..\..\src\Shared\StringUtils.pas',
  RegExpr in '..\..\src\Shared\RegExpr.pas',
  MathUtils in '..\..\src\OposWebkassa\units\MathUtils.pas',
  duPOSPrinter in 'units\duPOSPrinter.pas',
  WebkassaImpl in '..\..\src\OposWebkassa\units\WebkassaImpl.pas',
  SalesReceipt in '..\..\src\OposWebkassa\units\SalesReceipt.pas',
  ReceiptItem in '..\..\src\OposWebkassa\units\ReceiptItem.pas',
  OposEsc in '..\..\src\Opos\OposEsc.pas',
  TextDocument in '..\..\src\OposWebkassa\units\TextDocument.pas',
  OposPtr in '..\..\src\Opos\OposPtr.pas',
  StorePointIO_TLB in 'units\StorePointIO_TLB.pas',
  duWebkassaTest in 'units\duWebkassaTest.pas',
  PrinterParametersReg in '..\..\src\Shared\PrinterParametersReg.pas',
  PrinterLines in '..\..\src\OposWebkassa\units\PrinterLines.pas',
  uLkJSON in '..\..\src\Shared\uLkJSON.pas',
  VatRate in '..\..\src\Shared\VatRate.pas',
  OposPtrUtils in '..\..\src\Opos\OposPtrUtils.pas',
  OposPtrhi in '..\..\src\Opos\OposPtrhi.pas',
  duWebkassaImpl in 'units\duWebkassaImpl.pas',
  MockPosPrinter in '..\OposWebkassaTest\units\MockPosPrinter.pas';

{$R *.RES}

begin
  DecimalSeparator := '.';
  TGUITestRunner.RunTest(RegisteredTests);
end.
