program OposWebkassaTest;

uses
  FastMM4,
  SysUtils,
  TestFramework,
  GUITestRunner,
  LogFile in '..\..\src\Shared\LogFile.pas',
  Opos in '..\..\src\Opos\Opos.pas',
  OposUtils in '..\..\src\Opos\OposUtils.pas',
  OposEvents in '..\..\src\Opos\OposEvents.pas',
  OposFptr in '..\..\src\Opos\OposFptr.pas',
  OposFptrhi in '..\..\src\Opos\OposFptrhi.pas',
  Oposhi in '..\..\src\Opos\Oposhi.pas',
  OposStat in '..\..\src\Opos\OposStat.pas',
  OposSemaphore in '..\..\src\Opos\OposSemaphore.pas',
  OposFptrUtils in '..\..\src\Opos\OposFptrUtils.pas',
  OPOSException in '..\..\src\Opos\OposException.pas',
  WException in '..\..\src\Shared\WException.pas',
  WebkassaClient in '..\..\src\OposWebkassa\units\WebkassaClient.pas',
  JsonUtils in '..\..\src\Shared\JsonUtils.pas',
  FileUtils in '..\..\src\Shared\FileUtils.pas',
  OposEventsRCS in '..\..\src\Opos\OposEventsRCS.pas',
  DebugUtils in '..\..\src\Shared\DebugUtils.pas',
  OposWebkassaLib_TLB in '..\..\src\OposWebkassa\OposWebkassaLib_TLB.pas',
  OposServiceDevice19 in '..\..\src\Opos\OposServiceDevice19.pas',
  NotifyThread in '..\..\src\Shared\NotifyThread.pas',
  VersionInfo in '..\..\src\Shared\VersionInfo.pas',
  DriverError in '..\..\src\Shared\DriverError.pas',
  FiscalPrinterState in '..\..\src\OposWebkassa\units\FiscalPrinterState.pas',
  CustomReceipt in '..\..\src\OposWebkassa\units\CustomReceipt.pas',
  NonfiscalDoc in '..\..\src\OposWebkassa\units\NonfiscalDoc.pas',
  ServiceVersion in '..\..\src\Shared\ServiceVersion.pas',
  DeviceService in '..\..\src\Shared\DeviceService.pas',
  CashOutReceipt in '..\..\src\OposWebkassa\units\CashOutReceipt.pas',
  CashInReceipt in '..\..\src\OposWebkassa\units\CashInReceipt.pas',
  duWebkassaClient in 'units\duWebkassaClient.pas',
  OposPOSPrinter_CCO_TLB in '..\..\src\Opos\OposPOSPrinter_CCO_TLB.pas',
  PrinterParameters in '..\..\src\Shared\PrinterParameters.pas',
  TntIniFiles in '..\..\src\Shared\TntIniFiles.pas',
  SmIniFile in '..\..\src\Shared\SmIniFile.pas',
  StringUtils in '..\..\src\Shared\StringUtils.pas',
  RegExpr in '..\..\src\Shared\RegExpr.pas',
  MathUtils in '..\..\src\OposWebkassa\units\MathUtils.pas',
  WebkassaImpl in '..\..\src\OposWebkassa\units\WebkassaImpl.pas',
  SalesReceipt in '..\..\src\OposWebkassa\units\SalesReceipt.pas',
  ReceiptItem in '..\..\src\OposWebkassa\units\ReceiptItem.pas',
  OposEsc in '..\..\src\Opos\OposEsc.pas',
  TextDocument in '..\..\src\OposWebkassa\units\TextDocument.pas',
  OposPtr in '..\..\src\Opos\OposPtr.pas',
  duSalesReceipt in 'units\duSalesReceipt.pas',
  PrinterParametersReg in '..\..\src\Shared\PrinterParametersReg.pas',
  uLkJSON in '..\..\src\Shared\uLkJSON.pas',
  VatRate in '..\..\src\Shared\VatRate.pas',
  duTranslation in 'units\duTranslation.pas',
  duOposDevice in 'units\duOposDevice.pas',
  MockPosPrinter2 in 'units\MockPosPrinter2.pas',
  OposPtrUtils in '..\..\src\Opos\OposPtrUtils.pas',
  OposPtrhi in '..\..\src\Opos\OposPtrhi.pas',
  RCSEvents in 'units\RCSEvents.pas',
  RCSEvents_TLB in 'units\RCSEvents_TLB.pas',
  PosPrinterOA48 in '..\..\src\Shared\PosPrinterOA48.pas',
  uZintBarcode in '..\..\src\Shared\uZintBarcode.pas',
  uZintInterface in '..\..\src\Shared\uZintInterface.pas',
  POSPrinterLog in '..\..\src\Opos\POSPrinterLog.pas',
  duReceiptTemplate in 'units\duReceiptTemplate.pas',
  EscPrinterOA48 in '..\..\src\Shared\EscPrinterOA48.pas',
  ByteUtils in '..\..\src\Shared\ByteUtils.pas',
  PosWinPrinter in '..\..\src\Shared\PosWinPrinter.pas',
  PrinterPort in '..\..\src\Shared\PrinterPort.pas',
  SerialPort in '..\..\src\Shared\SerialPort.pas',
  DeviceNotification in '..\..\src\Shared\DeviceNotification.pas',
  PortUtil in '..\..\src\Shared\PortUtil.pas',
  TextReport in '..\..\src\Shared\TextReport.pas',
  SocketPort in '..\..\src\Shared\SocketPort.pas',
  SerialPorts in '..\..\src\Shared\SerialPorts.pas',
  ReceiptTemplate in '..\..\src\Shared\ReceiptTemplate.pas',
  MockPrinterPort in '..\..\src\Shared\MockPrinterPort.pas',
  RawPrinterPort in '..\..\src\Shared\RawPrinterPort.pas',
  Translation in '..\..\src\Shared\Translation.pas',
  duPrinterParameters in 'units\duPrinterParameters.pas',
  DirectIOAPI in '..\..\src\OposWebkassa\units\DirectIOAPI.pas',
  duWebkassaImpl3 in 'units\duWebkassaImpl3.pas',
  duTextDocument in 'units\duTextDocument.pas',
  xmlParser in '..\..\src\Shared\XMLParser.pas',
  MockPosPrinter in 'units\MockPosPrinter.pas',
  duWebkassaImpl4 in 'units\duWebkassaImpl4.pas',
  duOposUtils in 'units\duOposUtils.pas',
  duWebkassaImpl2 in 'units\duWebkassaImpl2.pas',
  duPosEscPrinter in 'units\duPosEscPrinter.pas',
  PrinterTypes in '..\..\src\Shared\PrinterTypes.pas',
  BarcodeUtils in '..\..\src\Shared\BarcodeUtils.pas',
  duEscPrinter in 'units\duEscPrinter.pas',
  duLogFile in 'units\duLogFile.pas',
  PosPrinterRongta in '..\..\src\Shared\PosPrinterRongta.pas',
  EscPrinterRongta in '..\..\src\Shared\EscPrinterRongta.pas',
  OposDevice in '..\..\src\Opos\OposDevice.pas',
  duWebkassaImpl in 'units\duWebkassaImpl.pas';

{$R *.RES}

begin
  TGUITestRunner.RunTest(RegisteredTests);
end.
