program OposTest;

uses
  Forms,
  fmuAbout in 'Fmu\fmuAbout.pas' {fmAbout},
  untPages in 'units\untPages.pas',
  untUtil in 'Units\untUtil.pas',
  AlignStrings in 'Units\AlignStrings.pas',
  OPOSDate in 'Units\OPOSDate.pas',
  OposUtils in '..\Opos\OposUtils.pas',
  Opos in '..\Opos\Opos.pas',
  OPOSException in '..\Opos\OposException.pas',
  OposFptr in '..\Opos\OposFptr.pas',
  OposFptrhi in '..\Opos\OposFptrhi.pas',
  Oposhi in '..\Opos\Oposhi.pas',
  OposEvents in '..\Opos\OposEvents.pas',
  OposFptrUtils in '..\Opos\OposFptrUtils.pas',
  LogFile in '..\Shared\LogFile.pas',
  VersionInfo in '..\Shared\VersionInfo.pas',
  DebugUtils in '..\Shared\DebugUtils.pas',
  OposDevice in '..\Opos\OposDevice.pas',
  PrinterEncoding in '..\Opos\PrinterEncoding.pas',
  BaseForm in '..\Shared\BaseForm.pas',
  FileUtils in '..\Shared\FileUtils.pas',
  SmIniFile in '..\Shared\SmIniFile.pas',
  PrinterParametersX in '..\Shared\PrinterParametersX.pas',
  StringUtils in '..\Shared\StringUtils.pas',
  DriverError in '..\Shared\DriverError.pas',
  OposFiscalPrinter_1_13_Lib_TLB in '..\Opos\OposFiscalPrinter_1_13_Lib_TLB.pas',
  OposFiscalPrinter in '..\Opos\OposFiscalPrinter.pas',
  WException in '..\Shared\WException.pas',
  TntIniFiles in '..\Shared\TntIniFiles.pas',
  RegExpr in '..\Shared\RegExpr.pas',
  OposWebkassaLib_TLB in '..\OposWebkassa\OposWebkassaLib_TLB.pas',
  PrinterParameters in '..\Shared\PrinterParameters.pas',
  PrinterParametersIni in '..\Shared\PrinterParametersIni.pas',
  fmuMain in 'Fmu\fmuMain.pas' {fmMain},
  fmuFiscalPrinter in 'Fmu\fmuFiscalPrinter.pas' {fmFiscalPrinter},
  fmuFptrGeneral in 'Fmu\fmuFptrGeneral.pas' {fmFptrGeneral},
  fmuFptrInfo in 'Fmu\fmuFptrInfo.pas' {fmFptrInfo},
  fmuFptrAddHeaderTrailer in 'Fmu\fmuFptrAddHeaderTrailer.pas' {fmFptrAddHeaderTrailer},
  fmuFptrDate in 'Fmu\fmuFptrDate.pas' {fmFptrDate},
  fmuFptrEvents in 'Fmu\fmuFptrEvents.pas' {fmFptrEvents},
  fmuFptrFiscalDocument in 'Fmu\fmuFptrFiscalDocument.pas' {fmFptrFiscalDocument},
  fmuFptrFiscalReports in 'Fmu\fmuFptrFiscalReports.pas' {fmFptrFiscalReports},
  fmuFptrGetData in 'Fmu\fmuFptrGetData.pas' {fmFptrGetData},
  fmuFptrNonFiscal in 'Fmu\fmuFptrNonFiscal.pas' {fmFptrNonFiscal},
  fmuFptrProperties in 'Fmu\fmuFptrProperties.pas' {fmFptrProperties},
  fmuFptrRecCash in 'Fmu\fmuFptrRecCash.pas' {fmFptrRecCash},
  fmuFptrReceipt in 'Fmu\fmuFptrReceipt.pas' {fmFptrReceipt},
  fmuFptrRecItem in 'Fmu\fmuFptrRecItem.pas' {fmFptrRecItem},
  fmuFptrRecItemAdjust in 'Fmu\fmuFptrRecItemAdjust.pas' {fmFptrRecItemAdjust},
  fmuFptrRecItemVoid in 'Fmu\fmuFptrRecItemVoid.pas' {fmFptrRecItemVoid},
  fmuFptrRecMessage in 'Fmu\fmuFptrRecMessage.pas' {fmFptrRecMessage},
  fmuFptrRecNotPaid in 'Fmu\fmuFptrRecNotPaid.pas' {fmFptrRecNotPaid},
  fmuFptrRecPackageAdjustment in 'Fmu\fmuFptrRecPackageAdjustment.pas' {fmFptrRecPackageAdjustment},
  fmuFptrRecPackageAdjustVoid in 'Fmu\fmuFptrRecPackageAdjustVoid.pas' {fmFptrRecPackageAdjustVoid},
  fmuFptrRecRefund in 'Fmu\fmuFptrRecRefund.pas' {fmFptrRecRefund},
  fmuFptrRecRefundVoid in 'Fmu\fmuFptrRecRefundVoid.pas' {fmFptrRecRefundVoid},
  fmuFptrRecSubtotal in 'Fmu\fmuFptrRecSubtotal.pas' {fmFptrRecSubtotal},
  fmuFptrRecSubtotalAdjustment in 'Fmu\fmuFptrRecSubtotalAdjustment.pas' {fmFptrRecSubtotalAdjustment},
  fmuFptrRecSubtotalAdjustVoid in 'Fmu\fmuFptrRecSubtotalAdjustVoid.pas' {fmFptrRecSubtotalAdjustVoid},
  fmuFptrRecTaxID in 'Fmu\fmuFptrRecTaxID.pas' {fmFptrRecTaxID},
  fmuFptrRecTotal in 'Fmu\fmuFptrRecTotal.pas' {fmFptrRecTotal},
  fmuFptrSetHeaderTrailer in 'Fmu\fmuFptrSetHeaderTrailer.pas' {fmFptrSetHeaderTrailer},
  fmuFptrSetline in 'Fmu\fmuFptrSetline.pas' {fmFptrSetLine},
  fmuFptrSetVatTable in 'Fmu\fmuFptrSetVatTable.pas' {fmFptrSetVatTable},
  fmuFptrSlipInsertion in 'Fmu\fmuFptrSlipInsertion.pas' {fmFptrSlipInsertion},
  fmuFptrStatistics in 'Fmu\fmuFptrStatistics.pas' {fmFptrStatistics},
  fmuFptrTest in 'Fmu\fmuFptrTest.pas' {fmFptrTest},
  fmuFptrTest2 in 'Fmu\fmuFptrTest2.pas' {fmFptrTest2},
  fmuFptrTraining in 'Fmu\fmuFptrTraining.pas' {fmFptrTraining},
  fmuFptrWritableProperties in 'Fmu\fmuFptrWritableProperties.pas' {fmFptrWritableProperties},
  fmuPosPrinter in 'Fmu\fmuPosPrinter.pas' {fmPosPrinter},
  fmuPrintRecItemRefund in 'Fmu\fmuPrintRecItemRefund.pas' {fmPrintRecItemRefund},
  fmuPrintRecItemRefundVoid in 'Fmu\fmuPrintRecItemRefundVoid.pas' {fmPrintRecItemRefundVoid},
  fmuPrintRecVoidItem in 'Fmu\fmuPrintRecVoidItem.pas' {fmPrintRecVoidItem},
  fmuPtrGeneral in 'Fmu\fmuPtrGeneral.pas' {fmPtrGeneral},
  DriverTest in 'Units\DriverTest.pas',
  NotifyThread in '..\Shared\NotifyThread.pas',
  OposPosPrinter in '..\Opos\OposPosPrinter.pas',
  OposPtrUtils in '..\Opos\OposPtrUtils.pas',
  OposPtr in '..\Opos\OposPtr.pas',
  OposPtrhi in '..\Opos\OposPtrhi.pas',
  PrinterParametersReg in '..\Shared\PrinterParametersReg.pas',
  VatCode in '..\Shared\VatCode.pas';

{$R *.RES}
{$R WindowsXP.RES}

begin
  Application.Initialize;
  Application.Title := 'OPOS test';
  Application.CreateForm(TfmMain, fmMain);
  Application.CreateForm(TfmFptrTest, fmFptrTest);
  Application.CreateForm(TfmFptrTest2, fmFptrTest2);
  Application.CreateForm(TfmPosPrinter, fmPosPrinter);
  Application.Run;
end.
